/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./src/**/*.{js,ts,jsx,tsx,mdx}"],
  theme: {
    extend: {
      colors: {
        // ─── Grepit semantic tokens (light + dark via CSS vars) ───
        // Drive everything with `bg-c-bg`, `text-c-text`, `border-c-line`
        // so the entire UI flips with the .dark class on <html>.
        "c-bg":           "var(--c-bg)",
        "c-bg-deep":      "var(--c-bg-deep)",
        "c-surface":      "var(--c-surface)",
        "c-surface-2":    "var(--c-surface-2)",
        "c-surface-3":    "var(--c-surface-3)",
        "c-surface-elev": "var(--c-surface-elev)",

        "c-line":         "var(--c-line)",
        "c-line-2":       "var(--c-line-2)",
        "c-line-3":       "var(--c-line-3)",

        "c-text":         "var(--c-text)",
        "c-text-2":       "var(--c-text-2)",
        "c-text-3":       "var(--c-text-3)",
        "c-text-4":       "var(--c-text-4)",

        "c-accent":       "var(--c-accent)",
        "c-accent-bright":"var(--c-accent-bright)",
        "c-accent-dim":   "var(--c-accent-dim)",
        "c-accent-soft":  "var(--c-accent-soft)",
        "c-accent-line":  "var(--c-accent-line)",
        "c-accent-glow":  "var(--c-accent-glow)",

        "c-peach":        "var(--c-peach)",
        "c-peach-soft":   "var(--c-peach-soft)",

        "c-overlay-1":    "var(--c-overlay-1)",
        "c-overlay-2":    "var(--c-overlay-2)",
        "c-overlay-3":    "var(--c-overlay-3)",
        "c-overlay-4":    "var(--c-overlay-4)",

        "c-success":      "var(--c-success)",
        "c-success-soft": "var(--c-success-soft)",

        "c-lime":         "var(--c-lime)",
        "c-lime-bright":  "var(--c-lime-bright)",
        "c-lime-dim":     "var(--c-lime-dim)",
        "c-lime-pastel":  "var(--c-lime-pastel)",
        "c-lime-soft":    "var(--c-lime-soft)",
        "c-lime-glow":    "var(--c-lime-glow)",
        "c-lime-line":    "var(--c-lime-line)",

        "c-sage":         "var(--c-sage)",
        "c-sage-soft":    "var(--c-sage-soft)",

        "c-coral":        "var(--c-coral)",
        "c-coral-soft":   "var(--c-coral-soft)",

        "c-vibrancy":     "var(--c-vibrancy)",

        // Raw brand swatches (when you need a fixed color regardless of theme)
        "brand-cream":    "#EEC679",
        "brand-green":    "#28C840",
        "brand-sage":     "#697C68",
        "brand-storm":    "#40433B",
        "brand-ink":      "#111511",
        "brand-vanta":    "#000100",

        // Back-compat alias to the old gp-* tokens — map to new system
        "gp-bg":        "var(--c-bg)",
        "gp-surface-1": "var(--c-surface)",
        "gp-surface-2": "var(--c-surface-2)",
        "gp-surface-3": "var(--c-surface-3)",
        "gp-text":      "var(--c-text)",
        "gp-text-2":    "var(--c-text-2)",
        "gp-text-3":    "var(--c-text-3)",
        "gp-line":      "var(--c-line)",
        "gp-line-2":    "var(--c-line-2)",
        "gp-line-3":    "var(--c-line-3)",
        "gp-mint":      "var(--c-accent)",
        "gp-mint-dim":  "var(--c-text-3)",
        "gp-lavender":  "var(--c-sage)",
        "gp-peach":     "var(--c-accent)",
        "gp-sky":       "var(--c-success)",
        "gp-coral":     "var(--c-coral)",
        "gp-rose":      "var(--c-accent-soft)",
        "gp-lime":      "var(--c-accent)",
        "gp-cyan":      "var(--c-success)",
        "gp-amber":     "var(--c-accent)",
        "gp-red":       "var(--c-coral)",

        // Legacy vb-* / d-* — ALL map to CSS vars so dashboard + app pages
        // inherit the warm palette and flip with light/dark automatically.
        "vb-bg":            "var(--c-bg)",
        "vb-bg1":           "var(--c-surface)",
        "vb-bg2":           "var(--c-surface-2)",
        "vb-bg3":           "var(--c-surface-3)",
        "vb-surface":       "var(--c-surface)",
        "vb-chat":          "var(--c-surface)",
        "vb-border":        "var(--c-line)",
        "vb-border2":       "var(--c-line-2)",
        "vb-border3":       "var(--c-line-3)",
        "vb-accent":        "var(--c-accent)",
        "vb-accent-dim":    "var(--c-accent-dim)",
        "vb-accent-bright": "var(--c-accent-bright)",
        "vb-green":         "var(--c-success)",
        "vb-violet":        "var(--c-sage)",
        "vb-cyan":          "var(--c-success)",
        "vb-amber":         "var(--c-peach)",
        "vb-red":           "var(--c-coral)",
        "vb-blue":          "var(--c-success)",
        "vb-pink":          "var(--c-peach)",
        "vb-ink":           "var(--c-text)",
        "vb-ink2":          "var(--c-text-2)",
        "vb-ink3":          "var(--c-text-3)",
        "vb-ink4":          "var(--c-text-4)",
        "vb-lime":          "var(--c-accent)",
        cream:              "var(--c-bg-deep)",
        sand:               "var(--c-surface-3)",
        ink:                "var(--c-text)",
        "ink-light":        "var(--c-text-2)",
        "ink-muted":        "var(--c-text-3)",
        "ink-faint":        "var(--c-text-4)",
        purple:             "var(--c-sage)",
        "purple-light":     "var(--c-sage)",
        lime:               "var(--c-accent)",
        "lime-light":       "var(--c-accent-bright)",
        blue:               "var(--c-success)",
        peach:              "var(--c-peach)",
        "d-bg":             "var(--c-bg)",
        "d-card":           "var(--c-surface)",
        "d-border":         "var(--c-line)",
        "d-text":           "var(--c-text)",
        "d-muted":          "var(--c-text-2)",
        "d-subtle":         "var(--c-text-3)",
      },
      fontFamily: {
        sans: ["var(--font-geist-sans)", "-apple-system", "BlinkMacSystemFont", "system-ui", "sans-serif"],
        mono: ["var(--font-geist-mono)", "'SF Mono'", "Menlo", "monospace"],
      },
      borderRadius: {
        // macOS-leaning radii — slightly rounder than before
        "c-xs": "6px",
        "c-sm": "10px",
        "c":    "12px",
        "c-md": "14px",
        "c-lg": "16px",
        "c-xl": "20px",
        // legacy
        "gp-sm":  "8px",
        "gp":     "12px",
        "gp-lg":  "14px",
        "gp-xl":  "16px",
        "vb":  "10px",
        "vb2": "12px",
        "vb3": "16px",
      },
      boxShadow: {
        "c-1":     "var(--shadow-1)",
        "c-2":     "var(--shadow-2)",
        "c-3":     "var(--shadow-3)",
        "c-focus": "0 0 0 3px var(--c-accent-soft)",
        // legacy
        "gp-1":     "var(--shadow-1)",
        "gp-2":     "var(--shadow-2)",
        "gp-3":     "var(--shadow-3)",
        "gp-focus": "0 0 0 3px var(--c-accent-soft)",
        "vb-sm":    "var(--shadow-1)",
        "vb-md":    "var(--shadow-2)",
        "vb-lg":    "var(--shadow-3)",
        "vb-xl":    "var(--shadow-3)",
        "vb-glow":  "0 0 0 1px var(--c-accent-line)",
      },
      animation: {
        "pulse-dot": "pulse-dot 2s ease infinite",
        "fade-in": "fadeIn 0.3s ease both",
        "slide-up": "slideUp 0.4s cubic-bezier(0.16,1,0.3,1) both",
        "blink": "blink 2s ease infinite",
        "marquee": "marquee 35s linear infinite",
      },
      keyframes: {
        "marquee": {
          "0%": { transform: "translateX(0)" },
          "100%": { transform: "translateX(-50%)" },
        },
        "pulse-dot": {
          "0%, 100%": { opacity: "1" },
          "50%": { opacity: "0.4" },
        },
        "fadeIn": {
          from: { opacity: "0" },
          to: { opacity: "1" },
        },
        "slideUp": {
          from: { opacity: "0", transform: "translateY(8px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
        "blink": {
          "0%, 100%": { opacity: "1" },
          "50%": { opacity: "0.3" },
        },
      },
    },
  },
  plugins: [],
};
