export default function TermsPage() {
  return (
    <div className="min-h-screen bg-vb-bg text-vb-ink px-6 md:px-8 py-24 max-w-[720px] mx-auto">
      <h1 className="text-[32px] font-semibold tracking-tight mb-2">Terms of Service</h1>
      <p className="text-[13px] text-vb-ink4 mb-10">Last updated: {new Date().toISOString().split("T")[0]}</p>

      <section className="mb-10">
        <h2 className="text-[18px] font-semibold mb-3">1. Acceptance of Terms</h2>
        <p className="text-[14px] text-vb-ink2 leading-relaxed">
          By accessing or using Vibo (&ldquo;the Service&rdquo;), you agree to be bound by these Terms of Service.
          If you do not agree, do not use the Service.
        </p>
      </section>

      <section className="mb-10">
        <h2 className="text-[18px] font-semibold mb-3">2. Description of Service</h2>
        <p className="text-[14px] text-vb-ink2 leading-relaxed">
          Vibo provides automated codebase analysis, AI-powered insights, security audits, and related tools.
          The Service analyzes GitHub repositories and uploaded code archives to generate reports, architecture maps,
          and interactive chat experiences.
        </p>
      </section>

      <section className="mb-10">
        <h2 className="text-[18px] font-semibold mb-3">3. User Accounts</h2>
        <p className="text-[14px] text-vb-ink2 leading-relaxed">
          You are responsible for maintaining the confidentiality of your account credentials and for all activities
          that occur under your account. You must provide accurate and complete information when creating an account.
        </p>
      </section>

      <section className="mb-10">
        <h2 className="text-[18px] font-semibold mb-3">4. Subscriptions and Billing</h2>
        <p className="text-[14px] text-vb-ink2 leading-relaxed">
          Vibo offers free and paid subscription tiers. Paid subscriptions (Pro) are billed monthly via Stripe.
          By subscribing to a paid plan, you authorize us to charge your payment method on a recurring basis until cancelled.
          You may cancel your subscription at any time through your billing portal. Cancellation takes effect at the end
          of the current billing period. No refunds are provided for partial months.
        </p>
      </section>

      <section className="mb-10">
        <h2 className="text-[18px] font-semibold mb-3">5. Acceptable Use</h2>
        <p className="text-[14px] text-vb-ink2 leading-relaxed">
          You agree not to use the Service to analyze repositories containing illegal content, malware, or content
          that violates third-party rights. We reserve the right to suspend or terminate access for violations.
        </p>
      </section>

      <section className="mb-10">
        <h2 className="text-[18px] font-semibold mb-3">6. Intellectual Property</h2>
        <p className="text-[14px] text-vb-ink2 leading-relaxed">
          The analysis results, reports, and insights generated by the Service are provided for your personal or
          internal business use. The underlying code analyzed remains the property of its respective owners.
          Vibo does not claim ownership over any code you submit for analysis.
        </p>
      </section>

      <section className="mb-10">
        <h2 className="text-[18px] font-semibold mb-3">7. Limitation of Liability</h2>
        <p className="text-[14px] text-vb-ink2 leading-relaxed">
          The Service is provided &ldquo;as is&rdquo; without warranties of any kind. Vibo shall not be liable for any
          damages arising from the use of or inability to use the Service, including but not limited to data loss,
          service interruptions, or inaccurate analysis results.
        </p>
      </section>

      <section className="mb-10">
        <h2 className="text-[18px] font-semibold mb-3">8. Changes to Terms</h2>
        <p className="text-[14px] text-vb-ink2 leading-relaxed">
          We reserve the right to modify these Terms at any time. Changes will be effective upon posting.
          Continued use of the Service after changes constitutes acceptance of the new Terms.
        </p>
      </section>

      <section className="mb-10">
        <h2 className="text-[18px] font-semibold mb-3">9. Contact</h2>
        <p className="text-[14px] text-vb-ink2 leading-relaxed">
          For questions about these Terms, contact us at{" "}
          <a href="mailto:hello@vibo.dev" className="text-vb-accent hover:underline">hello@vibo.dev</a>.
        </p>
      </section>
    </div>
  );
}
